services:
  local-server:
    build: .
    ports:
      - "3000:3000"
    volumes:
      # Mount directories (not files) to avoid mount type errors
      - ./public:/app/public
      - ./config:/app/config:rw
    environment:
      - NODE_ENV=production
      # Optional: Set a custom session secret for security
      - SESSION_SECRET=your-secret-key-here-change-this
    restart: unless-stopped
    # Run as root initially to fix permissions, then switch to node user
    # Alternative: use user mapping if host directories have correct ownership
    # user: "1000:1000"  # Uncomment and adjust if needed
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s