services:
  local-server:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./public:/app/public
      - ./config.json:/app/config.json
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s