#!/usr/bin/env node
/**
 * Mirror Daemon – Raspberry Pi Remote Management Agent
 *
 * Polls the Local-Server-Site-Pusher administration server for pending
 * commands, executes them locally, and reports results back.
 *
 * Supported commands
 * ------------------
 *   display_on        – Turn the HDMI display on
 *   display_off       – Turn the HDMI display off
 *   browser_restart   – Restart the kiosk browser (Chromium)
 *   dashboard_restart – Alias for browser_restart
 *   pi_reboot         – Reboot the Raspberry Pi
 *   pi_shutdown       – Shut down the Raspberry Pi
 *   config_update     – Write key/value pairs to daemon-config.json
 *   daemon_ping       – No-op health check; reports back immediately
 *
 * Authentication
 * --------------
 * Each daemon instance is identified by a unique bearer token that is
 * generated by the admin server when the device is registered.  The token
 * must be stored in the config file (never hard-coded).
 *
 * The daemon NEVER overwrites its config file during a config_update command;
 * it merges the provided keys into the existing file so that credentials and
 * site-specific settings are always preserved.
 *
 * Usage
 * -----
 *   node mirror-daemon.js [--config /path/to/config.json]
 *   node mirror-daemon.js --help
 */

'use strict';

const fs = require('fs');
const path = require('path');
const os = require('os');
const { execFile, spawn } = require('child_process');
const https = require('https');
const http = require('http');

// ---------------------------------------------------------------------------
// Version
// ---------------------------------------------------------------------------

const DAEMON_VERSION = '1.0.0';

// ---------------------------------------------------------------------------
// CLI arg parsing
// ---------------------------------------------------------------------------

const args = process.argv.slice(2);
if (args.includes('--help') || args.includes('-h')) {
  console.log(`
Mirror Daemon v${DAEMON_VERSION}
Usage: node mirror-daemon.js [options]

Options:
  --config <path>   Path to config file (default: ./daemon-config.json)
  --help, -h        Show this help message
`);
  process.exit(0);
}

const configArgIdx = args.indexOf('--config');
const CONFIG_PATH = configArgIdx !== -1 && args[configArgIdx + 1]
  ? path.resolve(args[configArgIdx + 1])
  : path.join(__dirname, 'daemon-config.json');

// ---------------------------------------------------------------------------
// Logging
// ---------------------------------------------------------------------------

const LOG_DIR = path.join(__dirname, 'logs');
const LOG_PATH = path.join(LOG_DIR, 'mirror-daemon.log');
const MAX_LOG_BYTES = 5 * 1024 * 1024; // 5 MB

function ensureLogDir() {
  if (!fs.existsSync(LOG_DIR)) {
    fs.mkdirSync(LOG_DIR, { recursive: true });
  }
}

function rotateLogs() {
  try {
    if (fs.existsSync(LOG_PATH)) {
      const stat = fs.statSync(LOG_PATH);
      if (stat.size >= MAX_LOG_BYTES) {
        const rotated = LOG_PATH + '.1';
        if (fs.existsSync(rotated)) fs.unlinkSync(rotated);
        fs.renameSync(LOG_PATH, rotated);
      }
    }
  } catch (_) { /* ignore rotation errors */ }
}

function log(level, message) {
  ensureLogDir();
  rotateLogs();
  const ts = new Date().toISOString();
  const line = `[${ts}] [${level.toUpperCase()}] ${message}\n`;
  const emoji = { INFO: 'ℹ️', WARN: '⚠️', ERROR: '❌', SUCCESS: '✅', DEBUG: '🔍' }[level.toUpperCase()] || '📝';
  console.log(`${emoji}  ${line.trim()}`);
  try {
    fs.appendFileSync(LOG_PATH, line, 'utf8');
  } catch (_) { /* best-effort */ }
}

const logger = {
  info: (msg) => log('INFO', msg),
  warn: (msg) => log('WARN', msg),
  error: (msg) => log('ERROR', msg),
  success: (msg) => log('SUCCESS', msg),
  debug: (msg) => log('DEBUG', msg),
};

// ---------------------------------------------------------------------------
// Config loading
// ---------------------------------------------------------------------------

/**
 * Load daemon configuration from JSON file.
 * Never throws – missing fields will cause early validation below.
 */
function loadConfig() {
  if (!fs.existsSync(CONFIG_PATH)) {
    logger.error(`Config file not found: ${CONFIG_PATH}`);
    logger.error('Copy daemon-config.template.json to daemon-config.json and fill in your values.');
    process.exit(1);
  }
  try {
    const raw = fs.readFileSync(CONFIG_PATH, 'utf8');
    return JSON.parse(raw);
  } catch (err) {
    logger.error(`Failed to parse config file: ${err.message}`);
    process.exit(1);
  }
}

/**
 * Merge key/value pairs into the config file without overwriting other keys.
 * This is used by the config_update command so that credentials are preserved.
 */
function mergeConfig(updates) {
  const existing = loadConfig();
  const merged = Object.assign({}, existing, updates);
  fs.writeFileSync(CONFIG_PATH, JSON.stringify(merged, null, 2), { mode: 0o600 });
  logger.info(`Config updated: ${Object.keys(updates).join(', ')}`);
}

let cfg = loadConfig();

// Validate required config keys
const REQUIRED_KEYS = ['serverUrl', 'deviceToken'];
for (const key of REQUIRED_KEYS) {
  if (!cfg[key]) {
    logger.error(`Required config key missing: ${key}`);
    process.exit(1);
  }
}

const SERVER_URL = cfg.serverUrl.replace(/\/$/, '');
const DEVICE_TOKEN = cfg.deviceToken;
const POLL_INTERVAL_MS = (cfg.pollIntervalSeconds || 30) * 1000;
const HEARTBEAT_INTERVAL_MS = (cfg.heartbeatIntervalSeconds || 60) * 1000;
const DISPLAY_ENV = cfg.displayEnv || ':0';
const BROWSER_CMD = cfg.browserCommand || 'chromium-browser';
const BROWSER_URL = cfg.browserUrl || 'http://localhost';
const PIR_PRESERVE = cfg.preservePirAutomation !== false; // default true

logger.info(`Mirror Daemon v${DAEMON_VERSION} starting…`);
logger.info(`Server: ${SERVER_URL}`);
logger.info(`Poll interval: ${POLL_INTERVAL_MS / 1000}s`);
logger.info(`PIR automation preservation: ${PIR_PRESERVE}`);

// ---------------------------------------------------------------------------
// HTTP helpers
// ---------------------------------------------------------------------------

/**
 * Make an HTTPS/HTTP request to the admin server.
 * Returns a Promise that resolves to { statusCode, body (parsed JSON) }.
 */
function apiRequest(method, urlPath, body = null) {
  return new Promise((resolve, reject) => {
    const fullUrl = SERVER_URL + urlPath;
    let urlObj;
    try {
      urlObj = new URL(fullUrl);
    } catch (err) {
      return reject(new Error(`Invalid server URL: ${fullUrl}`));
    }

    const isHttps = urlObj.protocol === 'https:';
    const options = {
      hostname: urlObj.hostname,
      port: urlObj.port || (isHttps ? 443 : 80),
      path: urlObj.pathname + (urlObj.search || ''),
      method: method.toUpperCase(),
      headers: {
        Authorization: `Bearer ${DEVICE_TOKEN}`,
        'Content-Type': 'application/json',
        'User-Agent': `MirrorDaemon/${DAEMON_VERSION}`,
      },
      // Allow self-signed certs in development (controlled via config)
      rejectUnauthorized: cfg.rejectUnauthorized !== false,
    };

    const bodyStr = body ? JSON.stringify(body) : null;
    if (bodyStr) {
      options.headers['Content-Length'] = Buffer.byteLength(bodyStr);
    }

    const transport = isHttps ? https : http;
    const req = transport.request(options, (res) => {
      let data = '';
      res.on('data', (chunk) => { data += chunk; });
      res.on('end', () => {
        try {
          resolve({ statusCode: res.statusCode, body: data ? JSON.parse(data) : {} });
        } catch (_) {
          resolve({ statusCode: res.statusCode, body: { raw: data } });
        }
      });
    });

    req.on('error', reject);
    req.setTimeout(15000, () => {
      req.destroy(new Error('Request timed out'));
    });

    if (bodyStr) req.write(bodyStr);
    req.end();
  });
}

// ---------------------------------------------------------------------------
// Command handlers
// ---------------------------------------------------------------------------

/**
 * Run a shell command and return { success, output, error }.
 * Requires the command to be in the ALLOWED_COMMANDS whitelist.
 */
const ALLOWED_SHELL_COMMANDS = {
  display_on_vcg: { cmd: 'vcgencmd', args: ['display_power', '1'] },
  display_off_vcg: { cmd: 'vcgencmd', args: ['display_power', '0'] },
  display_on_xrandr: { cmd: 'xrandr', args: ['--output', 'HDMI-1', '--auto'] },
  display_off_xrandr: { cmd: 'xrandr', args: ['--output', 'HDMI-1', '--off'] },
  reboot: { cmd: 'sudo', args: ['reboot'] },
  shutdown: { cmd: 'sudo', args: ['shutdown', '-h', 'now'] },
};

function runCommand(key, extraEnv = {}) {
  return new Promise((resolve) => {
    const entry = ALLOWED_SHELL_COMMANDS[key];
    if (!entry) {
      return resolve({ success: false, error: `Unknown command key: ${key}` });
    }
    const env = Object.assign({}, process.env, { DISPLAY: DISPLAY_ENV }, extraEnv);
    execFile(entry.cmd, entry.args, { env, timeout: 30000 }, (err, stdout, stderr) => {
      if (err) {
        resolve({ success: false, output: stdout, error: err.message || stderr });
      } else {
        resolve({ success: true, output: stdout || 'ok' });
      }
    });
  });
}

/**
 * Try vcgencmd first (native RPi); fall back to xrandr (X11).
 */
async function setDisplay(on) {
  const vcgKey = on ? 'display_on_vcg' : 'display_off_vcg';
  const xrandrKey = on ? 'display_on_xrandr' : 'display_off_xrandr';
  let result = await runCommand(vcgKey);
  if (!result.success) {
    logger.warn(`vcgencmd failed (${result.error}), trying xrandr…`);
    result = await runCommand(xrandrKey, { DISPLAY: DISPLAY_ENV });
  }
  return result;
}

/**
 * Restart the kiosk browser.
 */
function restartBrowser() {
  return new Promise((resolve) => {
    // Kill any existing browser instances
    execFile('pkill', ['-f', BROWSER_CMD], { timeout: 10000 }, () => {
      // Wait briefly then relaunch in background
      setTimeout(() => {
        try {
          const child = spawn(
            BROWSER_CMD,
            [
              '--noerrdialogs',
              '--disable-infobars',
              '--kiosk',
              BROWSER_URL,
            ],
            {
              detached: true,
              stdio: 'ignore',
              env: Object.assign({}, process.env, { DISPLAY: DISPLAY_ENV }),
            }
          );
          child.unref();
          resolve({ success: true, output: `Browser relaunched (pid ${child.pid})` });
        } catch (err) {
          resolve({ success: false, error: err.message });
        }
      }, 2000);
    });
  });
}

/**
 * Dispatch a command received from the server.
 */
async function executeCommand(command) {
  const { id, type, payload } = command;
  logger.info(`Executing command "${type}" (${id})`);

  let result;
  try {
    switch (type) {
      case 'display_on':
        result = await setDisplay(true);
        break;

      case 'display_off':
        // Respect PIR automation: if PIR is currently active we still honour
        // the remote command but log a notice so the operator is aware.
        if (PIR_PRESERVE) {
          logger.info('display_off: PIR automation is enabled – display will resume on motion');
        }
        result = await setDisplay(false);
        break;

      case 'browser_restart':
      case 'dashboard_restart':
        result = await restartBrowser();
        break;

      case 'pi_reboot':
        logger.warn('Rebooting Pi in 5 seconds…');
        await new Promise((r) => setTimeout(r, 5000));
        result = await runCommand('reboot');
        // If we get here the command failed (reboot would have killed the process)
        if (!result.success) {
          result = { success: false, error: result.error };
        }
        break;

      case 'pi_shutdown':
        logger.warn('Shutting down Pi in 5 seconds…');
        await new Promise((r) => setTimeout(r, 5000));
        result = await runCommand('shutdown');
        if (!result.success) {
          result = { success: false, error: result.error };
        }
        break;

      case 'config_update':
        if (!payload || typeof payload !== 'object' || Object.keys(payload).length === 0) {
          result = { success: false, error: 'config_update requires a non-empty payload' };
        } else {
          // Prevent overwriting the device token via remote command
          const safePayload = Object.assign({}, payload);
          delete safePayload.deviceToken;
          delete safePayload.serverUrl;
          if (Object.keys(safePayload).length === 0) {
            result = { success: false, error: 'config_update: only protected keys provided; nothing to update' };
          } else {
            mergeConfig(safePayload);
            // Reload cfg in memory
            cfg = loadConfig();
            result = { success: true, output: `Updated keys: ${Object.keys(safePayload).join(', ')}` };
          }
        }
        break;

      case 'daemon_ping':
        result = {
          success: true,
          output: JSON.stringify({
            version: DAEMON_VERSION,
            uptime: process.uptime(),
            platform: os.platform(),
            arch: os.arch(),
            hostname: os.hostname(),
            loadAvg: os.loadavg(),
          }),
        };
        break;

      default:
        result = { success: false, error: `Unrecognised command type: ${type}` };
    }
  } catch (err) {
    result = { success: false, error: err.message };
  }

  logger.info(`Command "${type}" result: ${result.success ? 'SUCCESS' : 'FAILED'} – ${result.output || result.error || ''}`);
  return result;
}

// ---------------------------------------------------------------------------
// Main poll loop
// ---------------------------------------------------------------------------

let consecutiveErrors = 0;
const MAX_BACKOFF_MS = 5 * 60 * 1000; // 5 minutes

async function pollOnce() {
  try {
    const { platform } = os;
    const resp = await apiRequest('GET', `/api/device/poll?platform=${encodeURIComponent(os.platform())}&version=${encodeURIComponent(DAEMON_VERSION)}`);

    if (resp.statusCode === 401) {
      logger.error('Authentication failed – check deviceToken in config. Stopping.');
      process.exit(1);
    }

    if (resp.statusCode !== 200) {
      throw new Error(`Server returned HTTP ${resp.statusCode}`);
    }

    consecutiveErrors = 0;
    const commands = resp.body.commands || [];

    if (commands.length > 0) {
      logger.info(`Received ${commands.length} command(s)`);
    }

    for (const command of commands) {
      const result = await executeCommand(command);
      // Report result back (best-effort; if it fails the server will timeout)
      try {
        await apiRequest('POST', '/api/device/result', {
          commandId: command.id,
          success: result.success,
          output: result.output || null,
          error: result.error || null,
        });
      } catch (err) {
        logger.warn(`Failed to report result for command ${command.id}: ${err.message}`);
      }
    }
  } catch (err) {
    consecutiveErrors++;
    const backoff = Math.min(POLL_INTERVAL_MS * consecutiveErrors, MAX_BACKOFF_MS);
    logger.warn(`Poll error (${consecutiveErrors} consecutive): ${err.message} – backing off ${backoff / 1000}s`);
    await new Promise((r) => setTimeout(r, backoff - POLL_INTERVAL_MS)); // extra wait on top of normal interval
  }
}

async function sendHeartbeat() {
  try {
    await apiRequest('POST', '/api/device/heartbeat', {
      platform: os.platform(),
      version: DAEMON_VERSION,
    });
  } catch (err) {
    logger.warn(`Heartbeat failed: ${err.message}`);
  }
}

// ---------------------------------------------------------------------------
// Start
// ---------------------------------------------------------------------------

(async function main() {
  // Send first heartbeat immediately
  await sendHeartbeat();

  // Poll loop
  const pollLoop = async () => {
    await pollOnce();
    setTimeout(pollLoop, POLL_INTERVAL_MS);
  };
  setTimeout(pollLoop, POLL_INTERVAL_MS);

  // Separate heartbeat timer
  setInterval(sendHeartbeat, HEARTBEAT_INTERVAL_MS);

  logger.success(`Daemon running – polling every ${POLL_INTERVAL_MS / 1000}s`);
})();

// ---------------------------------------------------------------------------
// Graceful shutdown
// ---------------------------------------------------------------------------

process.on('SIGTERM', () => {
  logger.info('SIGTERM received – shutting down gracefully');
  process.exit(0);
});

process.on('SIGINT', () => {
  logger.info('SIGINT received – shutting down gracefully');
  process.exit(0);
});

process.on('uncaughtException', (err) => {
  logger.error(`Uncaught exception: ${err.message}\n${err.stack}`);
  // Restart via systemd
  process.exit(1);
});

process.on('unhandledRejection', (reason) => {
  logger.error(`Unhandled rejection: ${reason}`);
});
